vich_uploader:
    db_driver: orm
    
    mappings:
        biens_image:
            uri_prefix: /images/immo
            upload_destination: '%kernel.project_dir%/public/images/immo'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        biens_fonds:
            uri_prefix: /images/fonds
            upload_destination: '%kernel.project_dir%/public/images/fonds'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        biens_logos:
            uri_prefix: /images/logos
            upload_destination: '%kernel.project_dir%/public/images/logos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        biens_larges:
            uri_prefix: /images/larges
            upload_destination: '%kernel.project_dir%/public/images/larges'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        biens_rappelfonds:
            uri_prefix: /images/rappelfonds
            upload_destination: '%kernel.project_dir%/public/images/rappelfonds'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        biens_regions:
            uri_prefix: /images/regions
            upload_destination: '%kernel.project_dir%/public/images/regions'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        biens_chambres:
            uri_prefix: /images/chambres
            upload_destination: '%kernel.project_dir%/public/images/chambres'
            namer: Vich\UploaderBundle\Naming\UniqidNamer            
        biens_communs:
            uri_prefix: /images/communs
            upload_destination: '%kernel.project_dir%/public/images/communs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        biens_proprios:
            uri_prefix: /images/proprios
            upload_destination: '%kernel.project_dir%/public/images/proprios'
            namer: Vich\UploaderBundle\Naming\UniqidNamer            
        interets_photo1:
            uri_prefix: /images/interets1
            upload_destination: '%kernel.project_dir%/public/images/interets1'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        interets_photo2:
            uri_prefix: /images/interets2
            upload_destination: '%kernel.project_dir%/public/images/interets2'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        interets_photo3:
            uri_prefix: /images/interets3
            upload_destination: '%kernel.project_dir%/public/images/interets3'
            namer: Vich\UploaderBundle\Naming\UniqidNamer