home:
    path: /accueil
    controller: App\Controller\HomeController::index

promesse:
    path: /promesse
    controller: App\Controller\HomeController::promesse
    
acheter:
    path: /ventes
    controller: App\Controller\VenteController::ventes
    
 
bien:
     path: /biens/{slug}-{id}
     controller: App\Controller\VenteController::voir
     requirements:
         slug: '[a-z0-9\-]*'
         
admin:
     path: /admin/gerer/
     controller: App\Controller\Admin\AdminProprieteController::index
     
adminbien:
     path: /admin/gerer/{id}
     controller: App\Controller\Admin\AdminProprieteController::edit
     
adminnouveaubien:
     path: /admin/nouveaubien/
     controller: App\Controller\Admin\AdminProprieteController::nouveau
     
supprimerbien:
     path: /admin/supprimer/{id}
     controller: App\Controller\Admin\AdminProprieteController::supprime
     
login:
    path: /login
    controller: App\Controller\SecurityController::login
    
logout:
    path: /logout

supprimerphoto:
     path: /admin/supprimerphoto/{id}
     controller: App\Controller\Admin\AdminPhotosController::supprimephoto
     